### ISSUE TITLE
Import hooks mechanism failing with Python 2

### ISSUE THREAD

**Issue by rth** [symerio/SiQt#4]
The current import hooks do not seem to work with Python 2. In particular, 

```
 python2 -c "import SiQt; SiQt.use('PyQt5'); import PyQt4.QtCore"
```

raises the following exception,

```
 Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/rth/src/SiQt/SiQt/siqt/importers.py", line 132, in load_module
       module = self._find_and_load_module(name, path)
    File "/home/rth/src/SiQt/SiQt/siqt/importers.py", line 181, in _find_and_load_module
     raise e
  SystemError: dynamic module not initialized properly
```

The [test suite](https://travis-ci.org/rth/SiQt) is failing for the same reason.  The underlying issue was posted as a [SO question](https://stackoverflow.com/questions/36731323/import-hooks-for-pyqt4-qtcore), as I'm running out of ideas here...

**Comment by rth** [comment]
Closing as not relevant anymore. QtPy should be used instead.
